# Extra data to be used in the database

NAMES = [
    'antonio',
    'jose',
    'francisco',
    'juan',
    'manuel',
    'pedro',
    'jesus',
    'angel',
    'miguel',
    'javier',
    'jose Antonio',
    'david',
    'carlos',
    'jose Luis',
    'alejandro',
    'miguel Angel',
    'francisco Javier',
    'rafael',
    'daniel',
    'juan Jose',
    'luis',
    'pablo',
    'juan Antonio',
    'joaquin',
    'sergio',
    'fernando',
    'juan Carlos',
    'andres',
    'jose Manuel',
    'jose Maria',
    'ramon',
    'raul',
    'alberto',
    'enrique',
    'alvaro',
    'vicente',
    'emilio',
    'francisco Jose',
    'diego',
    'julian',
    'jorge',
    'alfonso',
    'adrian',
    'ruben',
    'santiago',
    'ivan',
    'juan manuel',
    'pascual',
    'jose miguel',
    'mario'
]


SURNAMES = [
    'garcia',
    'martinez',
    'lopez',
    'sanchez',
    'gonzalez',
    'gomez',
    'fernandez',
    'moreno',
    'jimenez',
    'perez',
    'rodriguez',
    'navarro',
    'ruiz',
    'diaz',
    'serrano',
    'hernandez',
    'muñoz',
    'saez',
    'romero',
    'rubio',
    'alfaro',
    'molina',
    'lozano',
    'castillo',
    'picazo',
    'ortega',
    'morcillo',
    'cano',
    'marin',
    'cuenca',
    'garrido',
    'torres',
    'corcoles',
    'gil',
    'ortiz',
    'calero',
    'valero',
    'cebrian',
    'rodenas',
    'alarcon',
    'blazquez',
    'nuñez',
    'pardo',
    'moya',
    'tebar',
    'requena',
    'arenas',
    'ballesteros',
    'collado',
    'ramirez'
]

